name: test
on: [push, pull_request]
jobs:
  test:
    name: ${{ matrix.os }} Ruby ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        os:   ['ubuntu', 'macos', 'windows']
        ruby: ['3.1']
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Install (macos)
        if: ${{ matrix.os == 'macos' }}
        run: |
          brew -v
          bundle exec rake -T
      - name: Install (ubuntu)
        if: ${{ matrix.os == 'ubuntu' }}
        run: |
          gem install wasmer sorcerer
          sudo apt update -y
          bundle exec rake -T
      - name: Build and test with Rake
        run: |
          ruby examples/fib.rb